version: "3.1"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-root}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
